name: Build and Upload to Release

on:
  release:
    types:
      - created

jobs:
  release:
    name: Build and upload to release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

	# needed for uploading to release
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: findmyflags
            asset_name: findmyflags-linux
          - os: windows-latest
            artifact_name: findmyflags.exe
            asset_name: findmyflags-windows.exe
          - os: macos-latest
            artifact_name: findmyflags
            asset_name: findmyflags-macos

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Build
      run: gcc base64.c md5.c findmyflags.c -o findmyflags -g3 -Og -gdwarf-4

    - name: Upload to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}